static const unsigned char YugiUnused_todo[] = INCBIN_U8("src/overworld/entities/yugi_unused.4bpp");
static const unsigned char Yugi[] = INCBIN_U8("src/overworld/entities/yugi.4bpp");
static const unsigned char Atem[] = INCBIN_U8("src/overworld/entities/atem.4bpp");
static const unsigned char Seto[] = INCBIN_U8("src/overworld/entities/seto.4bpp");
static const unsigned char Joey[] = INCBIN_U8("src/overworld/entities/joey.4bpp");
static const unsigned char Marik[] = INCBIN_U8("src/overworld/entities/marik.4bpp");
static const unsigned char Ishizu[] = INCBIN_U8("src/overworld/entities/ishizu.4bpp");
static const unsigned char Mai[] = INCBIN_U8("src/overworld/entities/mai.4bpp");

// TODO: write a comment in the palette num(bank) array to fix the corresponding palettes (BUGFIX?)
//       same for yugi_running
static const unsigned char SolomonUnused_todo[] = INCBIN_U8("src/overworld/entities/solomon.4bpp");
static const unsigned char JoeyRunning_todo[] = INCBIN_U8("src/overworld/entities/joey_running.4bpp");

static const unsigned char Tea[] = INCBIN_U8("src/overworld/entities/tea.4bpp");
static const unsigned char Solomon[] = INCBIN_U8("src/overworld/entities/solomon.4bpp");
static const unsigned char Lumis[] = INCBIN_U8("src/overworld/entities/lumis.4bpp");
static const unsigned char Umbra[] = INCBIN_U8("src/overworld/entities/umbra.4bpp");
static const unsigned char Strings[] = INCBIN_U8("src/overworld/entities/strings.4bpp");
static const unsigned char Seeker[] = INCBIN_U8("src/overworld/entities/seeker.4bpp");
static const unsigned char Arkana[] = INCBIN_U8("src/overworld/entities/arkana.4bpp");
static const unsigned char Espa[] = INCBIN_U8("src/overworld/entities/espa.4bpp");
static const unsigned char Weevil[] = INCBIN_U8("src/overworld/entities/weevil.4bpp");
static const unsigned char Rex[] = INCBIN_U8("src/overworld/entities/rex.4bpp");
static const unsigned char Mako[] = INCBIN_U8("src/overworld/entities/mako.4bpp");
static const unsigned char Bonz[] = INCBIN_U8("src/overworld/entities/bonz.4bpp");
static const unsigned char Bakura[] = INCBIN_U8("src/overworld/entities/bakura.4bpp");
static const unsigned char Para[] = INCBIN_U8("src/overworld/entities/para.4bpp");
static const unsigned char Dox[] = INCBIN_U8("src/overworld/entities/dox.4bpp");
static const unsigned char Player[] = INCBIN_U8("src/overworld/entities/player.4bpp");
static const unsigned char NeoGhoul[] = INCBIN_U8("src/overworld/entities/neo_ghoul.4bpp");
static const unsigned char MimicOfDoom[] = INCBIN_U8("src/overworld/entities/mimic_of_doom.4bpp");
static const unsigned char PuppeteerOfDoom[] = INCBIN_U8("src/overworld/entities/puppeteer_of_doom.4bpp");
static const unsigned char Panik[] = INCBIN_U8("src/overworld/entities/panik.4bpp");
static const unsigned char MillenniumGuardian[] = INCBIN_U8("src/overworld/entities/millennium_guardian.4bpp");
static const unsigned char Pegasus[] = INCBIN_U8("src/overworld/entities/pegasus.4bpp");
static const unsigned char Shadi[] = INCBIN_U8("src/overworld/entities/shadi.4bpp");
static const unsigned char Roland[] = INCBIN_U8("src/overworld/entities/roland.4bpp");
static const unsigned char EspaBiggerBrother_todo[] = INCBIN_U8("src/overworld/entities/34.4bpp");
static const unsigned char EspaLittleBrother_todo[] = INCBIN_U8("src/overworld/entities/35.4bpp");

// TSC uses different palettes, so there is no correct palette for these in reshef
static const unsigned char TSC_Blue_Eyes_todo[] = INCBIN_U8("src/overworld/entities/tsc_blue_eyes.4bpp");
static const unsigned char TSC_Slifer_todo[] = INCBIN_U8("src/overworld/entities/tsc_slifer.4bpp");
static const unsigned char TSC_Ra_todo[] = INCBIN_U8("src/overworld/entities/tsc_ra.4bpp");

static const unsigned char Chevalier[] = INCBIN_U8("src/overworld/entities/chevalier.4bpp");
static const unsigned char s40[] = INCBIN_U8("src/overworld/entities/40.4bpp");
static const unsigned char Invisible[] = INCBIN_U8("src/overworld/entities/invisible.4bpp");
static const unsigned char Takeshi[] = INCBIN_U8("src/overworld/entities/takeshi.4bpp");
static const unsigned char s43[] = INCBIN_U8("src/overworld/entities/43.4bpp");
static const unsigned char s44[] = INCBIN_U8("src/overworld/entities/44.4bpp");
static const unsigned char s45[] = INCBIN_U8("src/overworld/entities/45.4bpp");
static const unsigned char DuelExpressConductor[] = INCBIN_U8("src/overworld/entities/duel_express_conductor.4bpp");
static const unsigned char s47[] = INCBIN_U8("src/overworld/entities/47.4bpp");
static const unsigned char s48[] = INCBIN_U8("src/overworld/entities/48.4bpp");
static const unsigned char Tristan[] = INCBIN_U8("src/overworld/entities/tristan.4bpp");
static const unsigned char s50[] = INCBIN_U8("src/overworld/entities/50.4bpp");
static const unsigned char s51[] = INCBIN_U8("src/overworld/entities/51.4bpp");
static const unsigned char s52[] = INCBIN_U8("src/overworld/entities/52.4bpp");
static const unsigned char s53[] = INCBIN_U8("src/overworld/entities/53.4bpp");
static const unsigned char Duke[] = INCBIN_U8("src/overworld/entities/duke.4bpp");
static const unsigned char Mokuba[] = INCBIN_U8("src/overworld/entities/mokuba.4bpp");
static const unsigned char Serenity[] = INCBIN_U8("src/overworld/entities/serenity.4bpp");
static const unsigned char Lucky[] = INCBIN_U8("src/overworld/entities/lucky.4bpp");
static const unsigned char s58[] = INCBIN_U8("src/overworld/entities/58.4bpp");
static const unsigned char s59[] = INCBIN_U8("src/overworld/entities/59.4bpp");

// TSC uses different palettes, so there is no correct palette for these in reshef
static const unsigned char TSC_Red_Eyes_todo[] = INCBIN_U8("src/overworld/entities/tsc_red_eyes.4bpp");
static const unsigned char TSC_Flame_Swordsman_todo[] = INCBIN_U8("src/overworld/entities/tsc_flame_swordsman.4bpp");

static const unsigned char s62[] = INCBIN_U8("src/overworld/entities/62.4bpp");
static const unsigned char BanditKeith[] = INCBIN_U8("src/overworld/entities/bandit_keith.4bpp");
static const unsigned char s64[] = INCBIN_U8("src/overworld/entities/64.4bpp");
static const unsigned char s65[] = INCBIN_U8("src/overworld/entities/65.4bpp");
static const unsigned char JeanClaudeMagnum[] = INCBIN_U8("src/overworld/entities/jean_claude_magnum.4bpp");
static const unsigned char s67[] = INCBIN_U8("src/overworld/entities/67.4bpp");
static const unsigned char s68[] = INCBIN_U8("src/overworld/entities/68.4bpp");
static const unsigned char s69[] = INCBIN_U8("src/overworld/entities/69.4bpp");
static const unsigned char s70[] = INCBIN_U8("src/overworld/entities/70.4bpp");
static const unsigned char s71[] = INCBIN_U8("src/overworld/entities/71.4bpp");
static const unsigned char s72[] = INCBIN_U8("src/overworld/entities/72.4bpp");
static const unsigned char s73[] = INCBIN_U8("src/overworld/entities/73.4bpp");
static const unsigned char s74[] = INCBIN_U8("src/overworld/entities/74.4bpp");
static const unsigned char s75[] = INCBIN_U8("src/overworld/entities/75.4bpp");
static const unsigned char s76[] = INCBIN_U8("src/overworld/entities/76.4bpp");
static const unsigned char s77[] = INCBIN_U8("src/overworld/entities/77.4bpp");
static const unsigned char s78[] = INCBIN_U8("src/overworld/entities/78.4bpp");
static const unsigned char s79[] = INCBIN_U8("src/overworld/entities/79.4bpp");
static const unsigned char s80[] = INCBIN_U8("src/overworld/entities/80.4bpp");
static const unsigned char s81[] = INCBIN_U8("src/overworld/entities/81.4bpp");
static const unsigned char s82[] = INCBIN_U8("src/overworld/entities/82.4bpp");
static const unsigned char s83[] = INCBIN_U8("src/overworld/entities/83.4bpp");
static const unsigned char s84[] = INCBIN_U8("src/overworld/entities/84.4bpp");
static const unsigned char s85[] = INCBIN_U8("src/overworld/entities/85.4bpp");
static const unsigned char s86[] = INCBIN_U8("src/overworld/entities/86.4bpp");
static const unsigned char s87[] = INCBIN_U8("src/overworld/entities/87.4bpp");
static const unsigned char s88[] = INCBIN_U8("src/overworld/entities/88.4bpp");
static const unsigned char PlayerRunning[] = INCBIN_U8("src/overworld/entities/player_running.4bpp");
static const unsigned char YugiRunning_todo[] = INCBIN_U8("src/overworld/entities/yugi_running.4bpp");
static const unsigned char s91[] = INCBIN_U8("src/overworld/entities/91.4bpp");
static const unsigned char s92[] = INCBIN_U8("src/overworld/entities/92.4bpp");
static const unsigned char s93[] = INCBIN_U8("src/overworld/entities/93.4bpp");
static const unsigned char s94[] = INCBIN_U8("src/overworld/entities/94.4bpp");
static const unsigned char s95[] = INCBIN_U8("src/overworld/entities/95.4bpp");
static const unsigned char s96[] = INCBIN_U8("src/overworld/entities/96.4bpp");
static const unsigned char Paradox[] = INCBIN_U8("src/overworld/entities/paradox.4bpp");
static const unsigned char Noah[] = INCBIN_U8("src/overworld/entities/noah.4bpp");
static const unsigned char MonkeyRobot[] = INCBIN_U8("src/overworld/entities/monkey_robot.4bpp");
static const unsigned char Rebecca[] = INCBIN_U8("src/overworld/entities/rebecca.4bpp");
static const unsigned char s101[] = INCBIN_U8("src/overworld/entities/101.4bpp");
static const unsigned char s102[] = INCBIN_U8("src/overworld/entities/102.4bpp");
static const unsigned char NightmarePenguin[] = INCBIN_U8("src/overworld/entities/nightmare_penguin.4bpp");
static const unsigned char DeepseaWarrior[] = INCBIN_U8("src/overworld/entities/deepsea_warrior.4bpp");
static const unsigned char RoboticKnight[] = INCBIN_U8("src/overworld/entities/robotic_knight.4bpp");
static const unsigned char JudgeMan[] = INCBIN_U8("src/overworld/entities/judge_man.4bpp");
static const unsigned char Jinzo[] = INCBIN_U8("src/overworld/entities/jinzo.4bpp");
static const unsigned char Kaibaman[] = INCBIN_U8("src/overworld/entities/kaibaman.4bpp");
static const unsigned char JohnnySteps[] = INCBIN_U8("src/overworld/entities/johnny_steps.4bpp");
static const unsigned char Arthur[] = INCBIN_U8("src/overworld/entities/arthur.4bpp"); //TODO: fix palette entry
static const unsigned char s111[] = INCBIN_U8("src/overworld/entities/111.4bpp");
static const unsigned char s112[] = INCBIN_U8("src/overworld/entities/112.4bpp");
static const unsigned char VideoCard[] = INCBIN_U8("src/overworld/entities/video_card.4bpp");
static const unsigned char s114[] = INCBIN_U8("src/overworld/entities/114.4bpp");
static const unsigned char s115[] = INCBIN_U8("src/overworld/entities/115.4bpp");
static const unsigned char s116[] = INCBIN_U8("src/overworld/entities/116.4bpp");
static const unsigned char s117[] = INCBIN_U8("src/overworld/entities/117.4bpp");
static const unsigned char s118[] = INCBIN_U8("src/overworld/entities/118.4bpp");
static const unsigned char s119[] = INCBIN_U8("src/overworld/entities/119.4bpp");
static const unsigned char s120[] = INCBIN_U8("src/overworld/entities/120.4bpp");
static const unsigned char s121[] = INCBIN_U8("src/overworld/entities/121.4bpp");
static const unsigned char ParaFlipping[] = INCBIN_U8("src/overworld/entities/para_flipping.4bpp");
static const unsigned char DoxFlipping[] = INCBIN_U8("src/overworld/entities/dox_flipping.4bpp");
static const unsigned char MediumRubble[] = INCBIN_U8("src/overworld/entities/medium_rubble.4bpp");
static const unsigned char SmallRubble[] = INCBIN_U8("src/overworld/entities/small_rubble.4bpp");
static const unsigned char BigRubble[] = INCBIN_U8("src/overworld/entities/big_rubble.4bpp");
static const unsigned char DoxWithMokuba[] = INCBIN_U8("src/overworld/entities/dox_with_mokuba.4bpp");
static const unsigned char s128[] = INCBIN_U8("src/overworld/entities/128.4bpp");
static const unsigned char BigFive[] = INCBIN_U8("src/overworld/entities/big_five.4bpp");
static const unsigned char Teddy[] = INCBIN_U8("src/overworld/entities/teddy.4bpp");
static const unsigned char s131[] = INCBIN_U8("src/overworld/entities/131.4bpp");
static const unsigned char s132[] = INCBIN_U8("src/overworld/entities/132.4bpp");
static const unsigned char s133[] = INCBIN_U8("src/overworld/entities/133.4bpp");
static const unsigned char s134[] = INCBIN_U8("src/overworld/entities/134.4bpp");
static const unsigned char s135[] = INCBIN_U8("src/overworld/entities/135.4bpp");
static const unsigned char s136[] = INCBIN_U8("src/overworld/entities/136.4bpp");
static const unsigned char s137[] = INCBIN_U8("src/overworld/entities/137.4bpp");
static const unsigned char s138[] = INCBIN_U8("src/overworld/entities/138.4bpp");
static const unsigned char Odion[] = INCBIN_U8("src/overworld/entities/odion.4bpp");
static const unsigned char FGD_Body[] = INCBIN_U8("src/overworld/entities/fgd_body.4bpp");
static const unsigned char FGD_Middle_Head[] = INCBIN_U8("src/overworld/entities/fgd_middle_head.4bpp");
static const unsigned char FGD_Tail[] = INCBIN_U8("src/overworld/entities/fgd_tail.4bpp");
static const unsigned char Fgd_Right_Heads[] = INCBIN_U8("src/overworld/entities/fgd_right_heads.4bpp");
static const unsigned char Fgd_Left_Heads[] = INCBIN_U8("src/overworld/entities/fgd_left_heads.4bpp");
static const unsigned char s145[] = INCBIN_U8("src/overworld/entities/145.4bpp");
static const unsigned char s146[] = INCBIN_U8("src/overworld/entities/146.4bpp");
static const unsigned char s147[] = INCBIN_U8("src/overworld/entities/147.4bpp");
static const unsigned char s148[] = INCBIN_U8("src/overworld/entities/148.4bpp");
static const unsigned char Butterfly[] = INCBIN_U8("src/overworld/entities/butterfly.4bpp");
static const unsigned char s150[] = INCBIN_U8("src/overworld/entities/150.4bpp");
static const unsigned char s151[] = INCBIN_U8("src/overworld/entities/151.4bpp");
static const unsigned char YugiWithMillenniumPuzzle[] = INCBIN_U8("src/overworld/entities/yugi_with_millennium_puzzle.4bpp");

/*
const unsigned char * gOverworldEntitySprites[] = {
  [SPRITE_YUGI_UNUSED] = YugiUnused,
  [SPRITE_YUGI] = Yugi,
  [SPRITE_ATEM] = Atem,
  [SPRITE_SETO] = Seto,
  [SPRITE_JOEY] = Joey,
  [SPRITE_MARIK] = Marik,
  [SPRITE_ISHIZU] = Ishizu,
  [SPRITE_MAI] = Mai,
  [SPRITE_SOLOMON_UNUSED_TODO] = SolomonUnused_todo,
  [SPRITE_JOEY_UNUSED_TODO] = JoeyUnused_todo,
  [SPRITE_TEA] = Tea,
  [SPRITE_SOLOMON] = Solomon,
  [SPRITE_LUMIS] = Lumis,
  [SPRITE_UMBRA] = Umbra,
  [SPRITE_STRINGS] = Strings,
  [SPRITE_SEEKER] = Seeker,
  [SPRITE_ARKANA] = Arkana,
  [SPRITE_ESPA] = Espa,
  [SPRITE_WEEVIL] = Weevil,
  [SPRITE_REX] = Rex,
  [SPRITE_MAKO] = Mako,
  [SPRITE_BONZ] = Bonz,
  [SPRITE_BAKURA] = Bakura,
  [SPRITE_PARA] = Para,
  [SPRITE_DOX] = Dox,
  [SPRITE_PLAYER] = Player,
  [SPRITE_NEO_GHOUL] = NeoGhoul,
  [SPRITE_MIMIC_OF_DOOM] = MimicOfDoom,
  [SPRITE_PUPPETEER_OF_DOOM] = PuppeteerOfDoom,
  [SPRITE_PANIK] = Panik,
  [SPRITE_MILLENNIUM_GUARDIAN] = MillenniumGuardian,
  [SPRITE_PEGASUS] = Pegasus,
  [SPRITE_SHADI] = Shadi,
  [SPRITE_ROLAND] = Roland,
  [SPRITE_ESPA_BIGGER_BROTHER_TODO] = EspaBiggerBrother_todo,
  [SPRITE_ESPA_LITTLE_BROTHER_TODO] = EspaLittleBrother_todo,
  [SPRITE_BLUE_EYES_UNUSED_TODO] = Blue_eyes_unused_todo,
  [SPRITE_SLIFER_TODO] = Slifer_todo,
  [SPRITE_RA_TODO] = Ra_todo,
  [SPRITE_CHEVALIER] = Chevalier,
  [SPRITE_40] = s40,
  [SPRITE_INVISIBLE] = Invisible,
  [SPRITE_TAKESHI] = Takeshi,
  [SPRITE_43] = s43,
  [SPRITE_44] = s44,
  [SPRITE_45] = s45,
  [SPRITE_DUEL_EXPRESS_CONDUCTOR] = DuelExpressConductor,
  [SPRITE_47] = s47,
  [SPRITE_48] = s48,
  [SPRITE_TRISTAN] = Tristan,
  [SPRITE_50] = s50,
  [SPRITE_51] = s51,
  [SPRITE_52] = s52,
  [SPRITE_53] = s53,
  [SPRITE_DUKE] = Duke,
  [SPRITE_MOKUBA] = Mokuba,
  [SPRITE_SERENITY] = Serenity,
  [SPRITE_LUCKY] = Lucky,
  [SPRITE_58] = s58,
  [SPRITE_59] = s59,
  [SPRITE_60] = s60,
  [SPRITE_61] = s61,
  [SPRITE_62] = s62,
  [SPRITE_BANDIT_KEITH] = BanditKeith,
  [SPRITE_0x64] = s64,
  [SPRITE_0x65] = s65,
  [SPRITE_JEAN_CLAUDE_MAGNUM] = JeanClaudeMagnum,
  [SPRITE_67] = s67,
  [SPRITE_68] = s68,
  [SPRITE_69] = s69,
  [SPRITE_70] = s70,
  [SPRITE_71] = s71,
  [SPRITE_72] = s72,
  [SPRITE_73] = s73,
  [SPRITE_74] = s74,
  [SPRITE_75] = s75,
  [SPRITE_76] = s76,
  [SPRITE_77] = s77,
  [SPRITE_78] = s78,
  [SPRITE_79] = s79,
  [SPRITE_80] = s80,
  [SPRITE_81] = s81,
  [SPRITE_82] = s82,
  [SPRITE_83] = s83,
  [SPRITE_84] = s84,
  [SPRITE_85] = s85,
  [SPRITE_86] = s86,
  [SPRITE_87] = s87,
  [SPRITE_88] = s88,
  [SPRITE_PLAYER_RUNNING] = PlayerRunning,
  [SPRITE_90] = s90,
  [SPRITE_91] = s91,
  [SPRITE_92] = s92,
  [SPRITE_93] = s93,
  [SPRITE_94] = s94,
  [SPRITE_95] = s95,
  [SPRITE_96] = s96,
  [SPRITE_PARADOX] = Paradox,
  [SPRITE_NOAH] = Noah,
  [SPRITE_MONKEY_ROBOT] = MonkeyRobot,
  [SPRITE_REBECCA] = Rebecca,
  [SPRITE_101] = s101,
  [SPRITE_102] = s102,
  [SPRITE_NIGHTMARE_PENGUIN] = NightmarePenguin,
  [SPRITE_DEEPSEA_WARRIOR] = DeepseaWarrior,
  [SPRITE_ROBOTIC_KNIGHT] = RoboticKnight,
  [SPRITE_JUDGE_MAN] = JudgeMan,
  [SPRITE_JINZO] = Jinzo,
  [SPRITE_KAIBAMAN] = Kaibaman,
  [SPRITE_JOHNNY_STEPS] = JohnnySteps,
  [SPRITE_ARTHUR] = Arthur,
  [SPRITE_111] = s111,
  [SPRITE_112] = s112,
  [SPRITE_VIDEO_CARD] = VideoCard,
  [SPRITE_114] = s114,
  [SPRITE_MILLENNIUM_NECKLACE] = s115,
  [SPRITE_MILLENNIUM_ROD] = s116,
  [SPRITE_MILLENNIUM_PUZZLE] = s117,
  [SPRITE_MILLENNIUM_KEY] = s118,
  [SPRITE_MILLENNIUM_EYE] = s119,
  [SPRITE_MILLENNIUM_RING] = s120,
  [SPRITE_MILLENNIUM_SCALE] = s121,
  [SPRITE_PARA_FLIPPING] = ParaFlipping,
  [SPRITE_DOX_FLIPPING] = DoxFlipping,
  [SPRITE_MEDIUM_RUBBLE] = MediumRubble,
  [SPRITE_SMALL_RUBBLE] = SmallRubble,
  [SPRITE_BIG_RUBBLE] = BigRubble,
  [SPRITE_DOX_WITH_MOKUBA] = DoxWithMokuba,
  [SPRITE_128] = s128,
  [SPRITE_BIG_FIVE] = BigFive,
  [SPRITE_TEDDY] = Teddy,
  [SPRITE_131] = s131,
  [SPRITE_132] = s132,
  [SPRITE_133] = s133,
  [SPRITE_134] = s134,
  [SPRITE_135] = s135,
  [SPRITE_136] = s136,
  [SPRITE_137] = s137,
  [SPRITE_138] = s138,
  [SPRITE_ODION] = Odion,
  [SPRITE_FGD_BODY] = FGD_Body,
  [SPRITE_FGD_MIDDLE_HEAD] = FGD_MiddleHead,
  [SPRITE_FGD_TAIL] = FGD_Tail,
  [SPRITE_FGD_RIGHT_HEADS] = Fgd_Right_Heads,
  [SPRITE_FGD_LEFT_HEADS] = Fgd_Left_Heads,
  [SPRITE_145] = s145,
  [SPRITE_146] = s146,
  [SPRITE_147] = s147,
  [SPRITE_148] = s148,
  [SPRITE_BUTTERFLY] = Butterfly,
  [SPRITE_150] = s150,
  [SPRITE_151] = s151,
  [SPRITE_YUGI_WITH_MILLENNIUM_PUZZLE] = sYugiWithMillenniumPuzzle
};
*/
